# Generated by Django 5.2 on 2025-05-05 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0007_alter_categories_status'),
        ('vendor', '0002_alter_vendor_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('last_date', models.DateTimeField()),
                ('min_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rfp_no', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=5)),
                ('categories', models.ManyToManyField(to='category.categories')),
                ('vendor', models.ManyToManyField(to='vendor.vendor')),
            ],
        ),
    ]
