# Generated by Django 5.2 on 2025-05-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfpDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfp',
            old_name='description',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='rfp',
            old_name='max_price',
            new_name='maximum_price',
        ),
        migrations.RenameField(
            model_name='rfp',
            old_name='min_price',
            new_name='minimum_price',
        ),
    ]
