# Generated by Django 5.2 on 2025-05-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfpDetails', '0002_rename_description_rfp_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfp',
            old_name='vendor',
            new_name='vendors',
        ),
    ]
