# Generated by Django 5.2 on 2025-05-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_categories_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, max_length=10),
        ),
    ]
