# Generated by Django 5.2 on 2025-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_categories_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
