# Generated by Django 5.2 on 2025-05-07 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfpDetails', '0003_rename_vendor_rfp_vendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendors_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('item_description', models.TextField()),
                ('total_cost', models.TextField()),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfpDetails.rfp')),
            ],
        ),
    ]
