# Generated by Django 5.2 on 2025-05-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        ('vendor', '0002_alter_vendor_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='vendor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
